export const INFINITE_SCROLL_IN_PROGRESS = "INFINITE_SCROLL_IN_PROGRESS"
export const INFINITE_SCROLL_COMPLETE = "INFINITE_SCROLL_COMPLETE"
export const INFINITE_SCROLL_ERROR = "INFINITE_SCROLL_ERROR"
