export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER_CURRENCY = "UPDATE_USER_CURRENCY";
export const UPDATE_USER_LIBRARY = "UPDATE_USER_LIBRARY";
export const CHANGE_PURCHASE_TRUE_FALSE = 'CHANGE_PURCHASE_TRUE_FALSE';
export const SHOW_ERROR_TO_USER = 'SHOW_ERROR_TO_USER';
