// PRODUCT CONSTANTS
export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FETCHQUERY = "FETCH_PRODUCTS_FETCHQUERY";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SET_PRODUCTS_TRUE = 'SET_PRODUCTS_TRUE';
export const SET_PRODUCTS_FALSE = 'SET_PRODUCTS_FALSE';
export const USE_STATE = 'USE_STATE';
